spring.application.name=ninjas
server.port = 8082
# Configurações do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/ninjas
spring.datasource.username=postgres
spring.datasource.password=postdba

#Driver reponsavel por fazer a conexão com o PostgresSQL
spring.datasource.drive-class-name=org.postgresql.Driver

# Atualize as tabelas do banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=update

# Exibir no terminal as consultas SQL geradas
spring.jpa.show-sql=true

# Formata o SQL exibido no console para facilitar leitura
spring.jpa.properties.hibernate.format_sql=true

# Define o tipo de banco utilizado(dialeto do PostgreSQL)
spring.jpa.database-plataform=org.hibernate.dialect.PostgreSQLDialect